"""Shared prompt components for all skill agents."""

from skills.prompts.sourcy_context import (
    SOURCY_BUSINESS_CONTEXT,
    ARTIFACT_GUIDELINES,
    SO_WHAT_INSTRUCTIONS,
    COMPETITOR_SUMMARY,
    TARGET_COUNTRIES_BLOCK,
    RECOMMENDATION_FORMAT_GUIDELINES,
    ROOT_CAUSE_REASONING,
    CROSS_AGENT_TRIGGERS,
    DIAGNOSTIC_OUTPUT_STANDARD,
    SIMPLE_LANGUAGE_RULES,
    STRUCTURED_OUTPUT_FORMAT,
    # Recommendation depth (Phase 4)
    BEFORE_AFTER_REQUIREMENT,
    STEP_BY_STEP_ACTION_FORMAT,
    TOOLTIP_AND_DRILLDOWN_DATA,
    # Operational depth (Phase 5)
    ERROR_HANDLING_PROTOCOL,
    CONFLICT_RESOLUTION_RULES,
    PRIORITIZATION_FRAMEWORK,
    REASONING_EXPLANATION,
    # New improvements
    MESSAGE_ALIGNMENT_FRAMEWORK,
    CHANNEL_CONTROLLABILITY_RULES,
)

from skills.prompts.content_engine_context import (
    CONTENT_ENGINE_BUSINESS_CONTEXT,
    CONTENT_QUALITY_RUBRIC,
    GEO_CITABILITY_RULES,
    EEAT_SCORING_GUIDE,
    CONTENT_CROSS_AGENT_TRIGGERS,
    CONTENT_OUTPUT_FORMAT,
)
