"""HTML differ — generates side-by-side diff views between original and proposed HTML.

Uses Python's built-in difflib for diff generation and unified patch creation.
All tools return JSON strings matching the project's @function_tool pattern.
"""

import difflib
import json
import re
from pathlib import Path

from agents import function_tool

import config

REVIEWS_OUTPUT_DIR = config.REVIEWS_OUTPUT_DIR

# Minimal CSS for a clean side-by-side diff view
_DIFF_CSS = """
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; background: #f8f9fa; }
  .diff-header { background: #1e293b; color: #f1f5f9; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; }
  .diff-header h2 { margin: 0; font-size: 16px; font-weight: 600; }
  .diff-header .meta { font-size: 12px; color: #94a3b8; }
  .diff-container { display: grid; grid-template-columns: 1fr 1fr; height: calc(100vh - 60px); }
  .diff-pane { overflow: auto; padding: 0; border-right: 1px solid #e2e8f0; }
  .diff-pane:last-child { border-right: none; }
  .pane-title { background: #f1f5f9; border-bottom: 1px solid #e2e8f0; padding: 8px 16px; font-size: 12px; font-weight: 600; color: #475569; text-transform: uppercase; letter-spacing: 0.05em; position: sticky; top: 0; z-index: 10; }
  table.diff { width: 100%; border-collapse: collapse; font-family: 'Fira Code', 'Cascadia Code', Consolas, monospace; font-size: 12px; }
  table.diff td { padding: 2px 12px; white-space: pre-wrap; word-break: break-word; vertical-align: top; }
  table.diff td.diff_header { background: #e2e8f0; color: #64748b; text-align: right; padding-right: 8px; user-select: none; min-width: 40px; }
  table.diff td.diff_next { display: none; }
  .diff_add { background: #dcfce7; }
  .diff_chg { background: #fef9c3; }
  .diff_sub { background: #fee2e2; }
  .diff_add span.diff_add { background: #86efac; }
  .diff_chg span.diff_chg { background: #fde047; }
  .diff_sub span.diff_sub { background: #fca5a5; }
  .stats { background: #1e293b; color: #94a3b8; padding: 8px 24px; font-size: 12px; display: flex; gap: 24px; }
  .stat-add { color: #4ade80; }
  .stat-remove { color: #f87171; }
  .stat-change { color: #facc15; }
</style>
"""


def _count_diff_stats(unified_diff: str) -> dict:
    """Count added/removed/changed lines from unified diff."""
    added = sum(1 for l in unified_diff.split("\n") if l.startswith("+") and not l.startswith("+++"))
    removed = sum(1 for l in unified_diff.split("\n") if l.startswith("-") and not l.startswith("---"))
    return {"lines_added": added, "lines_removed": removed}


def _make_side_by_side_html(
    original: str,
    proposed: str,
    original_label: str = "Original",
    proposed_label: str = "Proposed",
    title: str = "Page Diff",
) -> str:
    """Generate a side-by-side HTML diff using difflib.HtmlDiff."""
    original_lines = original.splitlines(keepends=True)
    proposed_lines = proposed.splitlines(keepends=True)

    differ = difflib.HtmlDiff(
        tabsize=2,
        wrapcolumn=100,
    )
    table_html = differ.make_table(
        original_lines,
        proposed_lines,
        fromdesc=original_label,
        todesc=proposed_label,
        context=True,
        numlines=3,
    )

    # Compute stats
    unified = "\n".join(difflib.unified_diff(
        original_lines, proposed_lines,
        fromfile=original_label, tofile=proposed_label, lineterm=""
    ))
    stats = _count_diff_stats(unified)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  {_DIFF_CSS}
</head>
<body>
  <div class="diff-header">
    <h2>{title}</h2>
    <span class="meta">Generated by Sourcy Marketing Agent</span>
  </div>
  <div class="stats">
    <span class="stat-add">+{stats['lines_added']} lines added</span>
    <span class="stat-remove">-{stats['lines_removed']} lines removed</span>
  </div>
  {table_html}
</body>
</html>"""

    return html


@function_tool
def generate_html_diff(
    original_content: str,
    proposed_content: str,
    ticket_id: str,
    page_slug: str,
    original_label: str = "Original",
    proposed_label: str = "Proposed",
) -> str:
    """Generate a side-by-side HTML diff between original and proposed page content.

    Saves the diff file to public/reviews/<ticket_id>/diffs/<page_slug>.diff.html
    Also saves a unified .patch file for git apply compatibility.

    Args:
        original_content: Original HTML or TSX content
        proposed_content: Proposed rewritten HTML or TSX content
        ticket_id: Ticket ID (used for output directory)
        page_slug: URL slug or filename (used for file naming, e.g., 'about' or 'blog-sourcing-guide')
        original_label: Label for left pane (default: 'Original')
        proposed_label: Label for right pane (default: 'Proposed')
    """
    # Sanitize slug for filename
    safe_slug = re.sub(r"[^\w\-]", "-", page_slug).strip("-")[:80]

    ticket_dir = REVIEWS_OUTPUT_DIR / ticket_id
    diffs_dir = ticket_dir / "diffs"
    patches_dir = ticket_dir / "patches"
    diffs_dir.mkdir(parents=True, exist_ok=True)
    patches_dir.mkdir(parents=True, exist_ok=True)

    # Side-by-side HTML diff
    diff_html = _make_side_by_side_html(
        original_content,
        proposed_content,
        original_label=original_label,
        proposed_label=proposed_label,
        title=f"Diff: {safe_slug}",
    )
    diff_file = diffs_dir / f"{safe_slug}.diff.html"
    diff_file.write_text(diff_html, encoding="utf-8")

    # Unified patch
    original_lines = original_content.splitlines(keepends=True)
    proposed_lines = proposed_content.splitlines(keepends=True)
    patch_lines = list(difflib.unified_diff(
        original_lines,
        proposed_lines,
        fromfile=f"a/{safe_slug}",
        tofile=f"b/{safe_slug}",
    ))
    patch_content = "".join(patch_lines)
    patch_file = patches_dir / f"{safe_slug}.patch"
    patch_file.write_text(patch_content, encoding="utf-8")

    stats = _count_diff_stats(patch_content)
    has_changes = bool(patch_content.strip())

    return json.dumps({
        "ticket_id": ticket_id,
        "page_slug": safe_slug,
        "diff_html_path": str(diff_file),
        "patch_path": str(patch_file),
        "has_changes": has_changes,
        "stats": stats,
        "diff_html_relative": f"diffs/{safe_slug}.diff.html",
        "patch_relative": f"patches/{safe_slug}.patch",
    })


@function_tool
def compare_files_diff(
    original_path: str,
    proposed_path: str,
    ticket_id: str,
    page_slug: str,
) -> str:
    """Generate an HTML diff by comparing two existing files on disk.

    Useful when original and proposed files are already saved to public/reviews/.

    Args:
        original_path: Absolute path to the original file
        proposed_path: Absolute path to the proposed file
        ticket_id: Ticket ID (for output directory)
        page_slug: Slug for the output filename
    """
    try:
        original_content = Path(original_path).read_text(encoding="utf-8", errors="ignore")
        proposed_content = Path(proposed_path).read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        return json.dumps({"error": f"Failed to read files: {str(e)}"})

    return generate_html_diff.__wrapped__(
        original_content,
        proposed_content,
        ticket_id,
        page_slug,
        original_label=f"Original ({Path(original_path).name})",
        proposed_label=f"Proposed ({Path(proposed_path).name})",
    )
